version: "3"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
  
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true

  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - "./data:/data/db"